unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-x


unbind '"'
unbind %

bind '|' split-window -h
bind - split-window -v

set -g default-terminal "tmux-256color"
set -g base-index 1

set-option -g status-position top

set -g @plugin "tmux-plugins/tpm"

set -g @plugin "rose-pine/tmux"
set -g @rose_pine_variant "main"

set -g @rose_pine_date_time "%x %X"
set -g @rose_pine_user "on"

run "~/.tmux/plugins/tpm/tpm"
